# vim:ft=kitty

# Shell
shell /usr/bin/nu

# Remote control
allow_remote_control socket-only
listen_on unix:${XDG_RUNTIME_DIR}/kitty

# Window settings
background_opacity 0.53
dim_opacity 0.85
background_blur 1
window_padding_width 8
dynamic_background_opacity yes
hide_window_decorations yes

# Font settings
font_family Agave Nerd Font Mono
bold_font Agave Nerd Font Bold
italic_font Agave Nerd Font Italic
bold_italic_font Agave Nerd Font Bold Italic
font_size 13.0

include ~/.local/state/caelestia/theme/kitty.conf
