# vim:ft=kitty

# Shell
shell /usr/bin/nu

# Window settings
background_opacity 0.53
dim_opacity 0.85
background_blur 1
window_padding_width 8
dynamic_background_opacity yes
hide_window_decorations yes

# Font settings
font_family agave Nerd Font Regular
bold_font agave Nerd Font Bold
italic_font agave Nerd Font Italic
bold_italic_font agave Nerd Font Bold Italic
font_size 12.0

include ~/.local/state/caelestia/theme/kitty.conf
