# vim:ft=kitty

# Shell
shell /usr/bin/nu

# Remote control
allow_remote_control socket-only
listen_on unix:${XDG_RUNTIME_DIR}/kitty

# Window settings
background_opacity 0.53
dim_opacity 0.85
background_blur 1
window_padding_width 8
dynamic_background_opacity yes
hide_window_decorations yes

# Font settings
font_family BerkeleyMono NF
bold_font BerkeleyMono NF Bd
italic_font BerkeleyMono NF Obl
bold_italic_font BerkeleyMono NF Bd Obl
font_size 10.5
font_features BerkeleyMonoNF-Rg +ss01 -calt
font_features BerkeleyMonoNF-Bd +ss01 -calt
font_features BerkeleyMonoNF-Obl +ss01 -calt
font_features BerkeleyMonoNF-OblBd +ss01 -calt
modify_font underline_position 4
modify_font underline_thickness 60%

include ~/.local/state/caelestia/theme/kitty.conf
